# Database
db.url=jdbc:mysql://localhost:3306/dosme?useSSL=false&serverTimezone=&characterEncoding=utf8
db.user=dosmesDB
db.pass=dosmedb
db.driver=com.mysql.cj.jdbc.Driver

# Security
jwt.secret=
otp.jwt.secret=
password.pepper=

# Email SMTP (v\u00ed d\u1ee5 Gmail SMTP)
email.host=smtp.gmail.com
email.port=587
email.user=
email.pass=

# Chatbot A.I
ai.provider=gemini
ai.api.key=
ai.api.base_url=https://generativelanguage.googleapis.com
ai.gemini.model=models/gemini-2.5-flash

# \u0110\u01b0\u1eddng d\u1eabn t\u01b0\u01a1ng \u0111\u1ed1i d\u00f9ng cho hi\u1ec3n th\u1ecb tr\u00ean web
avatar.web_path=/assets/images/avt/
# T\u00ean file \u1ea3nh m\u1eb7c \u0111\u1ecbnh (v\u00ed d\u1ee5 default.png)
avatar.default_file=default.png