# Database
db.url=jdbc:mysql://localhost:3306/dosme?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf8
db.user=dosmesDB
db.pass=dosmedb
db.driver=com.mysql.cj.jdbc.Driver

# Security
jwt.secret=
otp.jwt.secret=
password.pepper=CHANGE_ME_PEPPER

# Email SMTP (v\u00ed d\u1ee5 Gmail SMTP)
email.host=smtp.gmail.com
email.port=587
email.user=
email.pass=i

# Chatbot A.I
ai.api.key=
ai.api.base_url=https://generativelanguage.googleapis.com
ai.model=gemini-3.1-pro
