# Database
db.url=jdbc:mysql://localhost:3306/dosme?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf8
db.user=dosmesDB
db.pass=dosmedb
db.driver=com.mysql.cj.jdbc.Driver

# Security
jwt.secret=fK9zP2m7N5vB1xR8wQ4tL0jS6hG3aYdX
otp.jwt.secret=7nH4kC9sQ2mZ5jR1vP8wT0xL6fB3yG9u
password.pepper=CHANGE_ME_PEPPER

# Email SMTP (v\u00ed d\u1ee5 Gmail SMTP)
email.host=smtp.gmail.com
email.port=587
email.user=mojaverse.server@gmail.com
email.pass=ivqwiopxucnztiwe

# Chatbot A.I
ai.api.key=AIzaSyApUcVLmSEnIH4fgVmkRQBMrtsifTh0Sxg
ai.api.base_url=https://generativelanguage.googleapis.com
ai.model=gemini-3.1-pro